# Generated by Django 3.1 on 2020-08-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllegalImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('upload_time', models.DateTimeField()),
                ('video_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_number', models.DateTimeField()),
                ('motor_number', models.CharField(max_length=30)),
                ('people_number', models.CharField(max_length=30)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.video')),
            ],
        ),
        migrations.CreateModel(
            name='Illegal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('illegal_time', models.CharField(max_length=30)),
                ('illegal_carplate', models.CharField(max_length=30)),
                ('illegal_info', models.CharField(max_length=30)),
                ('illegalImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.illegalimage')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.video')),
            ],
        ),
    ]
