# Generated by Django 3.1 on 2020-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_illegal_illegalimage_trafficflow_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllegalData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=30)),
                ('upload_time', models.CharField(max_length=30)),
                ('illegal_time', models.CharField(max_length=30)),
                ('illegal', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=30)),
            ],
        ),
    ]
