# Generated by Django 3.1 on 2020-08-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200818_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficflow',
            name='car_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='motor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='people_number',
            field=models.IntegerField(),
        ),
    ]
