# Generated by Django 3.1 on 2020-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200821_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficflow',
            name='car_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='motor_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='people_number',
            field=models.CharField(max_length=30),
        ),
    ]
