# Generated by Django 3.1 on 2020-08-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_trafficflow_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficflow',
            name='car_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='motor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trafficflow',
            name='people_number',
            field=models.IntegerField(),
        ),
    ]
