# Generated by Django 3.1 on 2020-08-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20200821_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficflow',
            name='car_number',
            field=models.CharField(max_length=30),
        ),
    ]
