# Generated by Django 3.1 on 2020-08-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200821_1711'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Illegal',
        ),
    ]
