# Generated by Django 3.1 on 2020-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_delete_illegal'),
    ]

    operations = [
        migrations.CreateModel(
            name='IllegalStatistics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
