# Generated by Django 3.1 on 2020-08-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_auto_20200823_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.CharField(max_length=60),
        ),
    ]
