# Generated by Django 3.1 on 2020-08-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20200824_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videospeed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
